# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46b2d563004961b2baacd8ee13e0815a252f1eb6dbafdf76484756ed89af77d853f0a41adf4d8f7f21e336c0b70d9042a1540d90bc5995efc90d4daeac51333

test:
  secret_key_base: 0bd848b3c16f3d6d864732465bc16d7a460a243363946466d0ba72958493c0e170d31a092a396fa2927c3e8adc788103d0ac244097d6e2d23c0c083bef5e2911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
